/**
 * Body copy migrated verbatim from the live Wix pages (fetched 2026-07-26).
 *
 * Why this exists: the live pages hold genuinely good, human-written copy that
 * is worth keeping word-for-word — especially the four legal pages, which must
 * not be paraphrased. Only the *structure* is corrected.
 *
 * AUDIT FIX (heading hierarchy): the live pages go straight from <h1> to <h5>
 * with no <h3> or <h4> — 40 of 74 pages do this. Section headings are stored
 * here as level 2 so <RichBody> renders a valid h1 > h2 > h3 outline. Visual
 * size is handled by CSS, so the pages still look the same.
 *
 * Regenerate with tools/extract-copy.py after any Wix content edit.
 */
export type Block =
  | { t: 'h2'; text: string }
  | { t: 'h3'; text: string }
  | { t: 'p'; text: string }
  | { t: 'li'; text: string }

export const PAGE_BODY: Record<string, Block[]> = {
  'about': [
    { t: 'p', text: 'For years, Craig and Doreen Wambolt escaped the snowy New England winters by bringing their three children to Florida’s Space Coast — a place where the sand meets the surf and family memories come easily. They fell in love with Melbourne Beach, where they could spend mornings on the water and still be just a short drive from Orlando’s world-famous parks and attractions.' },
    { t: 'p', text: 'In 2020, the Wambolts made Melbourne their permanent home and set out to share the very experience that had brought their family so much joy. From that vision, The Florida Havens was born — a collection of private, oceanfront homes designed for families to reconnect, relax, and create lifelong memories.' },
    { t: 'p', text: 'The Havens at Beach Street welcomed its first guests in 2023, offering two luxury homes just steps from the shore. Two years later, The Havens at The Dunes opened in the spring of 2025, expanding the experience with another pair of beautifully appointed seaside retreats.' },
    { t: 'p', text: 'Today, The Florida Havens continues the Wambolts’ family tradition — where beachside serenity meets the excitement of nearby Orlando, and every stay feels like coming home to the coast.' },
  ],
  'accessibility-statement': [
    { t: 'p', text: 'Accessibility Statement' },
    { t: 'p', text: 'At The Florida Havens, we are committed to providing a welcoming and inclusive experience for all our guests. We strive to make our website, booking process, and properties as accessible as reasonably possible in accordance with the Americans with Disabilities Act (ADA), Web Content Accessibility Guidelines (WCAG) 2.1, and other applicable accessibility standards.' },
    { t: 'p', text: '1. Website Accessibility' },
    { t: 'p', text: 'Our website (www.thefloridahavens.com) is designed with accessibility in mind. We have implemented the following features:' },
    { t: 'p', text: 'Clear navigation and intuitive layouts compatible with screen readers and keyboard navigation.' },
    { t: 'p', text: 'Alternative text for images and descriptive links.' },
    { t: 'p', text: 'High color contrast and support for adjustable text sizes.' },
    { t: 'p', text: 'Optimization for major browsers and assistive technologies.' },
    { t: 'p', text: 'We regularly test and work to improve the accessibility of our website. If you encounter any barriers or have suggestions for improvement, please contact us using the details below.' },
    { t: 'p', text: '2. Property Accessibility' },
    { t: 'p', text: 'Our properties offer spacious, open layouts that can accommodate many guests with mobility or other needs. However, due to the unique coastal environment and architectural design of beachfront properties on a sea turtle reserve, full ADA accessibility cannot be guaranteed at every home.' },
    { t: 'p', text: 'Available features may include:' },
    { t: 'p', text: 'Wide doorways and open floor plans in select areas.' },
    { t: 'p', text: 'Ground-level access at certain properties.' },
    { t: 'p', text: 'Accessible parking spaces and EV chargers.' },
    { t: 'p', text: 'Important Note: Beach access, exterior stairs, multi-level interiors, and natural terrain may present challenges for guests with mobility impairments. We strongly encourage you to contact us before booking to discuss your specific accessibility needs. We will happily recommend the most suitable property and provide detailed information from our property guidebooks.' },
    { t: 'p', text: 'Security Cameras For guest safety and property security, exterior security cameras monitor entrances, driveways, and grounds. There are no interior cameras or audio recordings inside the homes.' },
    { t: 'p', text: '3. Our Commitment' },
    { t: 'p', text: 'We conduct periodic accessibility audits of our website and properties.' },
    { t: 'p', text: 'Our team is trained to assist guests with diverse needs.' },
    { t: 'p', text: 'We welcome feedback and will make reasonable accommodations where possible.' },
    { t: 'p', text: 'Contact Us For accessibility inquiries, accommodation requests, or feedback, please reach out:' },
    { t: 'p', text: 'The Florida Havens Email: relax@thefloridahavens.com Phone: (321) 209-0495' },
    { t: 'p', text: 'We aim to respond to accessibility requests within 48 hours.' },
  ],
  'beach-house-near-orlando-theme-parks': [
    { t: 'p', text: 'At The Florida Havens, you don’t have to choose between a relaxing beach escape and the thrilling adventures of Orlando’s world-class theme parks — you can enjoy both!' },
    { t: 'p', text: 'Nestled along Florida’s beautiful Space Coast, our properties offer the perfect balance: 🏖️ Secluded oceanfront peace and family-friendly comfort at your home base, and 🎡 Epic theme park excitement just a short drive away.' },
    { t: 'p', text: 'Whether you are dreaming of magical kingdoms, cinematic thrills, animal encounters, or all-inclusive adventure parks, Orlando delivers.' },
    { t: 'p', text: 'Below are easy links to the official ticket and planning pages for the most popular destinations, so you can book with confidence and convenience:' },
    { t: 'p', text: '🏰 Walt Disney World Resort — Magic Kingdom, EPCOT, Hollywood Studios & Animal Kingdom' },
    { t: 'p', text: 'Plan your visit or buy tickets online for single parks, Park Hopper options and more. Disney World Tickets & Planning – Official Walt Disney World Resort' },
    { t: 'p', text: 'BOOK DISNEY' },
    { t: 'p', text: '🎬 Universal Orlando Resort — Universal Studios, Islands of Adventure, Volcano Bay & Epic Universe' },
    { t: 'p', text: 'Explore multi-day and park-to-park options including The Wizarding World of Harry Potter™ and upcoming Epic Universe™ attractions. Universal Orlando Tickets & Packages – Official Site' },
    { t: 'p', text: 'BOOK UNIVERSAL' },
    { t: 'p', text: '🐧 SeaWorld Orlando — Rides, Shows & Animal Experiences' },
    { t: 'p', text: 'Purchase tickets and explore coaster thrills alongside unforgettable marine exhibits and animal encounters. SeaWorld Orlando Tickets & Tickets Info – Official Site' },
    { t: 'p', text: 'BOOK SEAWORLD' },
    { t: 'p', text: '🐬 Discovery Cove Orlando — All-Inclusive Tropical Adventure & Animal Encounters' },
    { t: 'p', text: 'Book an unforgettable all-inclusive day with activities like snorkeling with tropical fish and swimming with dolphins. Discovery Cove Orlando – Official Booking Page' },
    { t: 'p', text: 'BOOK DISCOVERY COVE' },
    { t: 'p', text: '🎟️ Great Multi-Park & Discount Ticket Resources' },
    { t: 'p', text: 'If you want all-in-one ticketing or discounted options, these sites offer combo passes, deals, and bundles for multiple parks and attractions:' },
    { t: 'p', text: '🌟 CityPASS® Orlando – bundled multi-park tickets at savings. Official Orlando CityPASS Tickets & Info' },
    { t: 'p', text: '🎢 AttractionTickets.com – Disney, Universal, SeaWorld & more in one checkout. Orlando Multi‑Park Tickets & Packages – AttractionTickets.com' },
    { t: 'p', text: '🎫 Undercover Tourist – discount tickets + local guides and tips. Discount Disney & Orlando Theme Park Tickets – Undercover Tourist' },
    { t: 'p', text: '🏡 Why Stay at The Florida Havens for Your Orlando Adventure?' },
    { t: 'p', text: '✔️ Relaxing Melbourne Beach & Indialantic oceanfront locations' },
    { t: 'p', text: '✔️ Peaceful retreat away from crowded tourist corridors' },
    { t: 'p', text: '✔️ Easy highway access for Orlando day trips' },
    { t: 'p', text: '✔️ The perfect balance of beach downtime and theme park excitement' },
    { t: 'p', text: '✔️ Spacious homes ideal for families and groups' },
    { t: 'p', text: 'Few places let you spend the morning on a quiet beach and the next day exploring Walt Disney World or Universal Orlando.' },
    { t: 'p', text: 'That’s the magic of staying on Florida’s Space Coast — close enough for adventure, far enough for true relaxation.' },
  ],
  'beach-house-near-sebastian-inlet': [
    { t: 'h2', text: 'Surf, Fish & Explore Florida’s Natural Coastline' },
    { t: 'p', text: 'Just a short scenic drive from The Florida Havens, Sebastian Inlet State Park is one of Florida’s most iconic outdoor destinations. Known for world-class surfing, exceptional fishing, and unspoiled coastal beauty, it’s a must-visit during your Space Coast stay.' },
    { t: 'p', text: 'When you book one of our beach homes in Melbourne Beach or Indialantic, you’re perfectly positioned to enjoy both:' },
    { t: 'p', text: '🏖️ Peaceful oceanfront relaxation' },
    { t: 'p', text: '🌴 And one of Florida’s most legendary coastal parks just minutes away' },
    { t: 'p', text: 'Whether you’re an early-morning surfer, an avid angler, or simply looking to explore nature trails and quiet beaches, Sebastian Inlet offers something for everyone.' },
    { t: 'p', text: '📍 Planning Your Visit' },
    { t: 'p', text: 'Drive time: Approximately 15 minutes from Melbourne Beach' },
    { t: 'p', text: 'Parking available inside Sebastian Inlet State Park' },
    { t: 'p', text: 'Modest park entrance fee applies' },
    { t: 'p', text: 'Best times to visit: Early morning for surfing & fishing, sunset for scenic views' },
    { t: 'p', text: '🎣 Things to Do at Sebastian Inlet:' },
    { t: 'p', text: '🏄‍♂️ World-Class Surfing' },
    { t: 'p', text: 'Sebastian Inlet is one of the most famous surf breaks on the East Coast. With consistent waves and a rich surf history, it attracts surfers from around the country.' },
    { t: 'p', text: 'Popular surf spots include:' },
    { t: 'p', text: 'First Peak' },
    { t: 'p', text: 'Second Peak' },
    { t: 'p', text: 'Monster Hole' },
    { t: 'p', text: 'Even if you don’t surf, it’s an incredible place to watch the action.' },
    { t: 'p', text: 'VISIT WEBSITE' },
    { t: 'p', text: '🎣 Inlet & Jetty Fishing' },
    { t: 'p', text: 'Known as one of Florida’s top fishing spots, the inlet offers opportunities to catch:' },
    { t: 'p', text: 'Snook' },
    { t: 'p', text: 'Pompano' },
    { t: 'p', text: 'Redfish' },
    { t: 'p', text: 'Tarpon' },
    { t: 'p', text: 'Flounder' },
    { t: 'p', text: 'Bluefish' },
    { t: 'p', text: 'And much more!' },
    { t: 'p', text: 'The north and south jetties are especially popular with anglers.' },
    { t: 'p', text: 'FISHING GUIDES' },
    { t: 'p', text: '🚤 Boating & Wildlife Viewing' },
    { t: 'p', text: 'The park connects the Indian River Lagoon to the Atlantic Ocean, making it a prime location for:' },
    { t: 'p', text: 'Boating' },
    { t: 'p', text: 'Kayaking' },
    { t: 'p', text: 'Dolphin sightings' },
    { t: 'p', text: 'Manatee spotting' },
    { t: 'p', text: '🏖️ Uncrowded Beaches' },
    { t: 'p', text: 'Sebastian Inlet’s beaches are more natural and less developed than many tourist areas — ideal for:' },
    { t: 'p', text: 'Shell collecting' },
    { t: 'p', text: 'Beach walks' },
    { t: 'p', text: 'Photography' },
    { t: 'p', text: 'Relaxing away from crowds' },
    { t: 'p', text: '🏕️ Nature Trails & History' },
    { t: 'p', text: 'Explore:' },
    { t: 'p', text: 'Scenic walking trails' },
    { t: 'p', text: 'McLarty Treasure Museum (local shipwreck history)' },
    { t: 'p', text: 'Coastal dune ecosystems' },
    { t: 'p', text: 'EXPLORE SEBASTIAN INLET' },
    { t: 'p', text: '🏡 Why Stay at The Florida Havens?' },
    { t: 'p', text: 'Staying at The Florida Havens means you can enjoy the adventure of Sebastian Inlet — then return to comfort and privacy.' },
    { t: 'p', text: '✔️ Direct beach access at your home base' },
    { t: 'p', text: '✔️ Full kitchens for preparing your catch of the day' },
    { t: 'p', text: '✔️ Spacious layouts ideal for families & groups' },
    { t: 'p', text: '✔️ Easy drive to Sebastian Inlet State Park' },
    { t: 'p', text: '✔️ A quieter alternative to crowded hotel areas' },
    { t: 'p', text: 'Many guests love starting the morning surfing or fishing at the inlet and ending the day relaxing on the private beach just steps from their vacation home. It’s the best of both worlds: adventure + serenity.' },
  ],
  'best-restaurants-near-melbourne-beach-indialantic': [
    { t: 'li', text: 'BREAKFAST & BRUNCH' },
    { t: 'li', text: 'LUNCH & CASUAL DINING' },
    { t: 'li', text: 'DINNER & UPSCALE DINING' },
    { t: 'li', text: 'DESSERTS' },
    { t: 'li', text: 'GROCERIES & MARKETS' },
    { t: 'p', text: 'When you stay at The Florida Havens, you’re perfectly positioned to enjoy some of the best restaurants near Melbourne Beach, Indialantic, and Downtown Melbourne.' },
    { t: 'p', text: 'As local hosts, we’ve curated this list based on personal favorites, trusted recommendations, and the spots our guests return to again and again. From fresh seafood and oceanfront dining to cozy breakfast cafés and upscale date-night destinations, these are the local dining experiences we genuinely recommend during your Space Coast stay.' },
    { t: 'h2', text: 'BREAKFAST / BRUNCH' },
    { t: 'h3', text: 'Backwater' },
    { t: 'p', text: 'Southern-inspired brunch favorite famous for chicken & waffles and craft cocktails.' },
    { t: 'h3', text: 'Sunnyside Cafe' },
    { t: 'p', text: 'Local favorite for hearty breakfasts, omelets, baked goods, and strong coffee near the beach.' },
    { t: 'h3', text: 'Around the World Bakery' },
    { t: 'p', text: 'European-style bakery café serving fresh pastries, breads, sandwiches, and light breakfast options.' },
    { t: 'h3', text: 'Rockies Café' },
    { t: 'p', text: 'A beloved breakfast spot serving classic favorites, fresh coffee, and generous portions — perfect before a morning beach walk.' },
    { t: 'h3', text: 'Café Surfinista' },
    { t: 'p', text: 'Bright, coastal café offering craft coffee, smoothies, breakfast bowls, and light bites in a relaxed beach-town setting.' },
    { t: 'h3', text: 'Mel\'s Tiki Café' },
    { t: 'p', text: 'A fun, laid-back tiki-style café known for creative breakfast plates and tropical vibes.' },
    { t: 'h2', text: 'LUNCH & CASUAL DINING' },
    { t: 'h3', text: 'Oceanside Pizza' },
    { t: 'p', text: 'Longtime local favorite for handcrafted pizzas, salads, and casual comfort food just minutes from the beach.' },
    { t: 'h3', text: 'Cuban Island' },
    { t: 'p', text: 'Authentic Cuban cuisine featuring bold flavors, slow-roasted meats, and traditional family recipes.' },
    { t: 'h3', text: 'Lily\'s Mediterranean' },
    { t: 'p', text: 'Fresh Mediterranean dishes with vibrant ingredients and healthy options.' },
    { t: 'h3', text: 'Drifters Surf Restro' },
    { t: 'p', text: 'Sushi Bar + Coastal Inspired Blackboard Specials' },
    { t: 'h3', text: 'Ichabod\'s Dockside' },
    { t: 'p', text: 'Waterside dining with burgers, seafood baskets, and casual marina views.' },
    { t: 'h3', text: 'Intracoastal Brewing' },
    { t: 'p', text: 'Local craft brewery with rotating taps and relaxed arts-district energy.' },
    { t: 'h3', text: 'Cyderman\'s BBQ' },
    { t: 'p', text: 'Smoked brisket, pulled pork, and hearty Southern comfort food.' },
    { t: 'h3', text: 'Mister 01 Pizza' },
    { t: 'p', text: 'Award winning artisan pizza made by renowned chef Renato Viola.' },
    { t: 'h3', text: 'Frigate\'s Bar & Grill' },
    { t: 'p', text: 'Indian River waterfront dining with seafood, sushi, and sunset cocktails.' },
    { t: 'h2', text: 'DINNER & UPSCALE DINING' },
    { t: 'h3', text: 'Café Coconut Cove' },
    { t: 'p', text: 'A rare and exceptional German restaurant just steps from your stay. Hearty European cuisine, authentic flavors, and an intimate atmosphere.' },
    { t: 'h3', text: 'The Fat Snook' },
    { t: 'p', text: 'Elevated coastal dining featuring fresh, locally sourced seafood and seasonal dishes. Known for clean ingredients and an allergy-friendly menu.' },
    { t: 'h3', text: 'Djon\'s Steak & Lobster' },
    { t: 'p', text: 'Elegant fine-dining experience offering premium steaks, fresh seafood, and attentive service.' },
    { t: 'h3', text: 'Island\'s Fish Grill' },
    { t: 'p', text: 'Casual yet refined seafood restaurant serving fresh, locally inspired dishes and locally caught fish daily.' },
    { t: 'h3', text: 'Ocean 302' },
    { t: 'p', text: 'Upscale coastal cuisine with a rotating seasonal menu and locally sourced ingredients.' },
    { t: 'h3', text: 'Crush XI' },
    { t: 'p', text: 'Wine bar and restaurant featuring creative small plates and a vibrant evening atmosphere.' },
    { t: 'h3', text: 'Umami Restaurant' },
    { t: 'p', text: 'Highly rated sushi and Japanese cuisine offering extensive rolls and creative plates.' },
    { t: 'h3', text: 'Boardwalk Bar & Grille' },
    { t: 'p', text: 'Locally Sourced, Internationally Inspired. Just steps from the breezy shores of Indialantic Beach,' },
    { t: 'h3', text: 'The Landing Rooftop' },
    { t: 'p', text: 'A stylish open-air rooftop bar offering panoramic views of Downtown Melbourne, craft cocktails, and an upscale atmosphere perfect for sunset.' },
    { t: 'h2', text: 'DESSERTS' },
    { t: 'h3', text: 'Beachside Creamery' },
    { t: 'p', text: 'A beloved local ice cream shop serving creative flavors, waffle cones, and classic favorites just minutes from the beach.' },
    { t: 'h3', text: 'The Fat Donkey' },
    { t: 'p', text: 'Premium ice cream, milkshakes, and decadent desserts in a fun arts-district setting.' },
    { t: 'h3', text: 'Love Bugs Bakery' },
    { t: 'p', text: 'Fresh baked donuts, pastries, and sweet treats made daily — perfect for a morning indulgence or late-night dessert run.' },
    { t: 'h2', text: 'GROCERIES & MARKETS' },
    { t: 'h3', text: 'Jungle Organic' },
    { t: 'p', text: 'A locally loved natural foods market offering organic produce, supplements, smoothies, and specialty health items.' },
    { t: 'h3', text: 'Djon\'s Village Market' },
    { t: 'p', text: 'Djon’s Village Market is a convenient Indialantic specialty market offering gourmet groceries, fresh prepared foods, wine, and beach-day essentials just minutes from the ocean.' },
    { t: 'h3', text: 'Walmart' },
    { t: 'p', text: 'Convenient for groceries, beach gear, household items, and last-minute necessities all in one stop.' },
    { t: 'h3', text: 'Publix' },
    { t: 'p', text: 'The go-to grocery store for most locals and visitors. Fresh produce, seafood, bakery items, deli meals, and everything you need for a beach vacation.' },
    { t: 'h3', text: 'Melbourne Beach Market' },
    { t: 'p', text: 'A small, convenient local market perfect for quick stops, snacks, wine, and essentials without driving far.' },
    { t: 'h3', text: 'Sprouts Farmers Market' },
    { t: 'p', text: 'Great for organic produce, specialty items, fresh meats, and healthy options.' },
    { t: 'p', text: '🏡 Why Stay at The Florida Havens?' },
    { t: 'p', text: '✔️ Minutes from the best restaurants in Melbourne Beach & Indialantic' },
    { t: 'p', text: '✔️ Walkable dining options just steps from your stay' },
    { t: 'p', text: '✔️ Easy access to Downtown Melbourne’s food & nightlife scene' },
    { t: 'p', text: '✔️ Oceanfront setting perfect for sunset dinners and late-night strolls' },
    { t: 'p', text: '✔️ Full kitchens for preparing fresh local seafood at home' },
    { t: 'p', text: 'Few places offer the ability to grab craft coffee in the morning, enjoy oceanfront seafood at sunset, and end the evening with rooftop cocktails — all within minutes of your beach retreat.' },
    { t: 'p', text: 'Staying at The Florida Havens means you’re perfectly positioned to experience the very best dining the Space Coast has to offer — without ever feeling far from the sand.' },
  ],
  'cape-canaveral-cruise-port-beach-stay': [
    { t: 'p', text: 'One of the best-kept secrets about staying at The Florida Havens is our proximity to Port Canaveral — one of the busiest cruise ports in the world.' },
    { t: 'p', text: 'Located just about 1 hour north of Melbourne Beach and Indialantic, our properties offer the perfect place to:' },
    { t: 'p', text: '🌴 Relax before your cruise departure' },
    { t: 'p', text: '🏖️ Recover after your cruise returns' },
    { t: 'p', text: '🚢 Turn your sailing into a full Florida vacation' },
    { t: 'p', text: 'Instead of staying in a crowded port hotel, enjoy a peaceful oceanfront retreat on Florida’s beautiful Space Coast — with easy highway access straight to the cruise terminals.' },
    { t: 'p', text: 'Whether you\'re sailing to the Bahamas, Caribbean, or beyond, our beach homes make the ideal home base before and/or after your adventure at sea.' },
    { t: 'p', text: '🚗 Getting to Port Canaveral' },
    { t: 'p', text: 'Approximate drive time: 45 minutes' },
    { t: 'p', text: 'Direct highway access via I-95 and FL-528' },
    { t: 'p', text: 'Take Uber/Lyft or drive your rental car. Ample parking available at the cruise terminals (advance reservations recommended)' },
    { t: 'p', text: '🗺️ Cruise Lines Sailing from Port Canaveral' },
    { t: 'p', text: 'Below are the major cruise lines that regularly depart from Port Canaveral, along with official booking links for easy planning.' },
    { t: 'p', text: '🏰 Disney Cruise Line' },
    { t: 'p', text: 'Magical sailings to the Bahamas and Caribbean — including visits to Disney’s private island, Castaway Cay and Lighthouse Point. Official Booking & Planning: https://disneycruise.disney.go.com/' },
    { t: 'p', text: 'BOOK DISNEY CRUISE' },
    { t: 'p', text: '⚓ Royal Caribbean International' },
    { t: 'p', text: 'Home to some of the largest cruise ships in the world, offering short Bahamas getaways and extended Caribbean itineraries. Official Booking & Planning: https://www.royalcaribbean.com/' },
    { t: 'p', text: 'BOOK ROYAL CARIBBEAN' },
    { t: 'p', text: '🎉 Carnival Cruise Line' },
    { t: 'p', text: 'Fun, family-friendly cruises with frequent departures to the Bahamas and Caribbean. Official Booking & Planning: https://www.carnival.com/' },
    { t: 'p', text: 'BOOK CARNIVAL' },
    { t: 'p', text: '🌊 Norwegian Cruise Line' },
    { t: 'p', text: 'Flexible cruise options with freestyle dining and Caribbean sailings from Port Canaveral.' },
    { t: 'p', text: 'Official Booking & Planning: https://www.ncl.com/' },
    { t: 'p', text: 'BOOK NORWEGIAN' },
    { t: 'p', text: '🛳️ MSC Cruises' },
    { t: 'p', text: 'European-style cruising with modern ships and competitive pricing on Caribbean routes.' },
    { t: 'p', text: 'Official Booking & Planning: https://www.msccruisesusa.com/' },
    { t: 'p', text: 'BOOK MSC' },
    { t: 'p', text: '💼 Why Stay at The Florida Havens Before or After Your Cruise?' },
    { t: 'p', text: '✔️ Avoid crowded port hotels' },
    { t: 'p', text: '✔️ Enjoy direct beach access' },
    { t: 'p', text: '✔️ Spacious homes ideal for families & groups' },
    { t: 'p', text: '✔️ Peaceful setting after busy theme parks or cruise travel' },
    { t: 'p', text: '✔️ Easy drive to Port Canaveral (approx. 60 minutes)' },
    { t: 'p', text: 'Many guests choose to:' },
    { t: 'p', text: 'Arrive 1–2 days early to avoid travel stress' },
    { t: 'p', text: 'Stay after disembarkation to extend vacation mode' },
    { t: 'p', text: 'Combine a Disney cruise with Orlando theme parks and a beach retreat' },
    { t: 'p', text: 'You truly get the best of all worlds.' },
  ],
  'local-attractions-melbourne-beach': [
    { t: 'p', text: 'Melbourne Beach & Indialantic' },
    { t: 'p', text: 'Located along Florida’s beautiful Space Coast, Melbourne Beach and Indialantic offer the perfect balance of relaxation and adventure. When you stay at The Florida Havens, you’re not just booking a beach house — you’re positioning yourself near some of Florida’s most exciting destinations.' },
    { t: 'p', text: 'From world-famous theme parks and cruise departures to elite sports complexes and natural coastal wonders, everything is within easy reach of your peaceful oceanfront retreat.' },
    { t: 'p', text: 'Whether you’re planning a family vacation, a tournament trip, a surf getaway, or a cruise extension, here are the top attractions near our properties.' },
    { t: 'p', text: '🌴 Major Destinations Within Easy Reach of The Florida Havens:' },
    { t: 'p', text: '🎢 Orlando Theme Parks (Approx. 1–2 hour drive)' },
    { t: 'p', text: 'Experience the magic of:' },
    { t: 'p', text: 'Walt Disney World' },
    { t: 'p', text: 'Universal Orlando Resort' },
    { t: 'p', text: 'SeaWorld Orlando' },
    { t: 'p', text: 'Discovery Cove' },
    { t: 'p', text: 'And so much more!' },
    { t: 'p', text: 'Many guests choose to combine beach relaxation with a day trip to the parks.' },
    { t: 'p', text: '👉 Learn more about visiting Orlando from Melbourne Beach & Indialantic:' },
    { t: 'p', text: 'VISIT ORLANDO' },
    { t: 'p', text: '🚢 Cape Canaveral & Port Canaveral (Approx. 45 minute drive)' },
    { t: 'p', text: 'One of the busiest cruise ports in the world, Port Canaveral is home to:' },
    { t: 'p', text: 'Disney Cruise Line' },
    { t: 'p', text: 'Royal Caribbean' },
    { t: 'p', text: 'Carnival Cruise Line' },
    { t: 'p', text: 'Norwegian Cruise Line' },
    { t: 'p', text: 'MSC Cruises' },
    { t: 'p', text: 'Avoid crowded port hotels and enjoy a peaceful beach stay before or after your cruise.' },
    { t: 'p', text: '👉 Explore our Cape Canaveral cruise guide:' },
    { t: 'p', text: 'BOOK YOUR CRUISE' },
    { t: 'p', text: '🚀 Florida’s Space Coast & Kennedy Space Center (Approx. 45–60 Minutes)' },
    { t: 'p', text: 'Curious why this area is called the Space Coast? Just north of Melbourne Beach, Kennedy Space Center and Cape Canaveral are home to NASA missions, SpaceX launches, and decades of space history.' },
    { t: 'p', text: 'Tour the Kennedy Space Center Visitor Complex or plan your stay around a live rocket launch — often visible from nearby beaches.' },
    { t: 'p', text: '👉 View our Space Coast & rocket launch guide:' },
    { t: 'p', text: 'EXPLORE SPACE COAST' },
    { t: 'p', text: '🌊 Sebastian Inlet State Park (Approx. 20 Minutes)' },
    { t: 'p', text: 'Known for:' },
    { t: 'p', text: 'World-class surfing' },
    { t: 'p', text: 'Exceptional fishing' },
    { t: 'p', text: 'Wildlife viewing' },
    { t: 'p', text: 'Scenic beaches' },
    { t: 'p', text: 'Sebastian Inlet offers a more natural, untouched side of Florida’s coastline.' },
    { t: 'p', text: '👉 Discover Sebastian Inlet activities:' },
    { t: 'p', text: 'EXPLORE SEBASTIAN INLET' },
    { t: 'p', text: '⚾ USSSA Space Coast Complex (Approx. 20 Minutes)' },
    { t: 'p', text: 'Traveling for a baseball or softball tournament? The USSSA Space Coast Complex in Melbourne hosts thousands of athletes and families every year.' },
    { t: 'p', text: 'Stay close to the action while enjoying the comfort of a private beach home.' },
    { t: 'p', text: '👉 View our USSSA tournament lodging guide:' },
    { t: 'p', text: 'USSSA COMPLEX GUIDE' },
    { t: 'p', text: '🦒 Brevard Zoo (Approx. 20 Minute drive)' },
    { t: 'p', text: 'Highlights include:' },
    { t: 'p', text: 'Kayaking through animal habitats' },
    { t: 'p', text: 'Giraffe feedings' },
    { t: 'p', text: 'Treetop Trek aerial adventure course' },
    { t: 'p', text: 'Expedition Africa & Rainforest Revealed exhibits' },
    { t: 'p', text: 'Paddling trail through the zoo grounds' },
    { t: 'p', text: 'Unlike large metropolitan zoos, Brevard Zoo offers a more personal and walkable experience — making it perfect for a half-day outing between beach time and other adventures. Perfect for families with young children.' },
    { t: 'p', text: '👉 Explore our guide to visiting Brevard Zoo:' },
    { t: 'p', text: 'VISIT BREVARD ZOO' },
    { t: 'p', text: '🌅 Melbourne Beach & Indialantic: Local Gems' },
    { t: 'p', text: 'Local Highlights:' },
    { t: 'p', text: 'Sea turtle nesting season (May–October)' },
    { t: 'p', text: 'Uncrowded beaches perfect for sunrise walks' },
    { t: 'p', text: 'Archie Carr National Wildlife Refuge' },
    { t: 'p', text: 'Historic Downtown Melbourne' },
    { t: 'p', text: 'Eau Gallie Arts District' },
    { t: 'p', text: 'Golf Courses' },
    { t: 'p', text: 'And much more!' },
    { t: 'p', text: 'If you’re seeking a slower pace and more natural surroundings, The Florida Havens deliver a peaceful experience.' },
    { t: 'p', text: 'EXPLORE LOCAL AREA' },
    { t: 'p', text: '🍽️ Best Restaurants Near Melbourne Beach (Minutes Away)' },
    { t: 'p', text: 'Highlights include:' },
    { t: 'p', text: 'Oceanfront seafood and sunset dining' },
    { t: 'p', text: 'Cozy breakfast cafés and local coffee shops' },
    { t: 'p', text: 'Walkable dinner spots near the beach' },
    { t: 'p', text: 'Upscale date-night restaurants' },
    { t: 'p', text: 'Casual breweries and waterfront bars' },
    { t: 'p', text: 'From fresh-caught fish to rooftop cocktails and charming neighborhood cafés, Melbourne Beach, Indialantic, and Downtown Melbourne offer incredible dining options just minutes from your stay. Perfect for everything from relaxed beach lunches to special evening celebrations.' },
    { t: 'p', text: '👉 Explore our Local Eats dining guide:' },
    { t: 'p', text: 'SEE LOCAL EATS' },
  ],
  'privacy-policy': [
    { t: 'p', text: 'At The Florida Havens, we are committed to protecting your privacy while delivering an exceptional luxury vacation experience. This Privacy Policy explains how we collect, use, store, protect, and share your personal information when you interact with our website, book a stay, or communicate with us.' },
    { t: 'p', text: 'This policy applies to bookings made through our website or the Guesty booking platform. While you also agree to Guesty’s platform Privacy Policy, this Rental Privacy Policy governs our direct relationship with you as a guest.' },
    { t: 'p', text: '1. Information We Collect' },
    { t: 'p', text: 'We collect only the information necessary to process your booking and provide excellent service:' },
    { t: 'p', text: 'Personal Information: Name, email address, phone number, billing address, and payment details.' },
    { t: 'p', text: 'Booking Details: Reservation dates, property selected, number of guests, special requests, and travel preferences.' },
    { t: 'p', text: 'Website Usage Data: IP address, browser and device information, pages visited, and interaction data collected via cookies and analytics tools (e.g., Google Analytics).' },
    { t: 'p', text: 'Communication Data: Inquiries, feedback, or messages sent through contact forms or email.' },
    { t: 'p', text: 'We do not knowingly collect data from children under 18. Our services are intended for adults.' },
    { t: 'p', text: '2. How We Collect Information' },
    { t: 'p', text: 'Directly from you when you book, inquire, or communicate with us.' },
    { t: 'p', text: 'Automatically through cookies, web beacons, and analytics tools on our website.' },
    { t: 'p', text: 'From third parties such as payment processors or the Guesty booking platform when you make a reservation.' },
    { t: 'p', text: '3. How We Use Your Information' },
    { t: 'p', text: 'We use your information to:' },
    { t: 'p', text: 'Process and manage your booking, payments, and check-in/check-out.' },
    { t: 'p', text: 'Communicate with you about your reservation and provide support.' },
    { t: 'p', text: 'Personalize your experience and fulfill special requests.' },
    { t: 'p', text: 'Improve our website and services through analytics.' },
    { t: 'p', text: 'Comply with legal obligations (tax reporting, safety regulations, etc.).' },
    { t: 'p', text: 'Send important booking-related updates (and, with your consent, occasional promotional messages).' },
    { t: 'p', text: '4. Security Cameras' },
    { t: 'p', text: 'For the safety and security of our guests and properties, exterior security cameras are installed at our properties. These cameras monitor only exterior areas (entrances, driveway, and grounds). There are no interior cameras or recordings of any kind inside the homes.' },
    { t: 'p', text: '5. How We Share Your Information' },
    { t: 'p', text: 'We do not sell your personal information. We may share it only as follows:' },
    { t: 'p', text: 'With trusted service providers (payment processors, cleaning teams, maintenance vendors, Guesty) who are contractually obligated to protect your data.' },
    { t: 'p', text: 'When required by law (court order, subpoena, tax authorities, etc.).' },
    { t: 'p', text: 'To protect the safety of the property, guests, or staff (e.g., enforcing House Rules).' },
    { t: 'p', text: '6. Data Security' },
    { t: 'p', text: 'We use industry-standard security measures including SSL encryption for transactions, access controls, and regular monitoring. While we strive to protect your data, no system is completely secure.' },
    { t: 'p', text: '7. Data Retention' },
    { t: 'p', text: 'Booking and payment records: Retained for up to 7 years to meet tax and legal requirements.' },
    { t: 'p', text: 'Marketing/communication consent: Retained until you withdraw consent.' },
    { t: 'p', text: 'Website analytics: Anonymized data may be kept longer for improvement purposes.' },
    { t: 'p', text: 'You may request deletion of your data where permitted by law.' },
    { t: 'p', text: '8. Your Rights Depending on your location (including rights under GDPR, CCPA/CPRA, or other applicable laws), you may have the right to:' },
    { t: 'p', text: 'Access, correct, or delete your personal information.' },
    { t: 'p', text: 'Object to or restrict certain processing.' },
    { t: 'p', text: 'Data portability.' },
    { t: 'p', text: 'Opt out of marketing communications.' },
    { t: 'p', text: 'To exercise these rights, contact us using the details below. We will respond within 30 days.' },
    { t: 'p', text: '9. Cookies and Tracking' },
    { t: 'p', text: 'Our website uses essential cookies for booking functionality and analytics cookies to understand visitor behavior. You can manage cookie preferences through your browser settings. Disabling cookies may affect site functionality.' },
    { t: 'p', text: '10. Third-Party Links and Platforms' },
    { t: 'p', text: 'Our site may contain links to external services. We are not responsible for their privacy practices. When you book through Guesty, their platform privacy policy also applies to data processed by them.' },
    { t: 'p', text: '11. International Data Transfers' },
    { t: 'p', text: 'Your data is stored in the United States. We take appropriate safeguards to protect international transfers where required.' },
    { t: 'p', text: '12. Updates to This Policy' },
    { t: 'p', text: 'We may update this Privacy Policy periodically. Changes will be posted here with a new effective date. Significant updates will be communicated to guests with active bookings.' },
    { t: 'p', text: '13. Contact Us' },
    { t: 'p', text: 'For any questions, concerns, or to exercise your privacy rights, please contact us:' },
    { t: 'p', text: 'The Florida Havens Email: relax@thefloridahavens.com Phone: (321) 209-0495' },
    { t: 'p', text: 'We aim to respond to general inquiries within 48 hours and privacy rights requests within 30 days.' },
  ],
  'refund-policy': [
    { t: 'p', text: 'Refund & Cancellation Policy' },
    { t: 'p', text: 'At The Florida Havens, we strive to provide clear, fair, and consistent policies for your luxury beachfront vacation. This Refund & Cancellation Policy forms part of our Terms and Conditions and applies to all bookings made through our website or the Guesty booking platform.' },
    { t: 'p', text: '1. Cancellation by Guests' },
    { t: 'p', text: 'Cancellations made 60 days or more before check-in: Full refund of total amount paid toward reservation at time of cancellation, minus a 5% processing fee. Processing fee is 5% of the total reservation amount.' },
    { t: 'p', text: 'Cancellations made fewer than 60 days before check-in: No refund. We may, at our sole discretion, offer a credit for a future stay (subject to availability and blackout dates).' },
    { t: 'p', text: 'No-Shows: The entire stay will be charged with no refund.' },
    { t: 'p', text: '2. Modifications to Reservations' },
    { t: 'p', text: 'Any changes to booking dates, properties, or guest counts are treated as a cancellation and new booking, subject to the cancellation policy above, current availability, and applicable rate changes.' },
    { t: 'p', text: '3. Early Departure & Termination' },
    { t: 'p', text: 'Voluntary early departure: No refund or credit for unused nights.' },
    { t: 'p', text: 'Termination due to violation of House Rules, Terms and Conditions, or applicable laws: No refund and possible forfeiture of the security deposit.' },
    { t: 'p', text: '5. Cancellations or Changes by The Florida Havens' },
    { t: 'p', text: 'In the rare event we must cancel or significantly alter your reservation due to property issues (maintenance, safety concerns, etc.), we will offer a full refund or comparable rebooking at no extra cost.' },
    { t: 'p', text: '6. Force Majeure' },
    { t: 'p', text: 'Events beyond our reasonable control (hurricanes, severe weather, pandemics, government orders, etc.) are addressed in our Terms and Conditions. We will work with you on rescheduling or a partial credit/refund at our sole discretion. No full refunds will be issued solely for weather-related concerns.' },
    { t: 'p', text: '7. Travel Insurance' },
    { t: 'p', text: 'We strongly recommend purchasing travel insurance that covers trip cancellation, interruption, medical emergencies, and personal property. This provides the best protection for unforeseen events not covered by our policy.' },
    { t: 'p', text: '8. Processing Refunds' },
    { t: 'p', text: 'Approved refunds are processed to the original payment method within 7–10 business days.' },
    { t: 'p', text: 'Actual receipt time depends on your bank or payment provider.' },
    { t: 'p', text: 'All refunds (where applicable) exclude processing fees already charged.' },
    { t: 'p', text: '9. How to Cancel or Request Changes' },
    { t: 'p', text: 'Submit cancellation or modification requests by emailing relax@thefloridahavens.com. Cancellations are effective upon our written confirmation.' },
  ],
  'stay-near-brevard-zoo-melbourne-beach-house': [
    { t: 'h2', text: 'A Wildly Fun Family Experience on the Space Coast' },
    { t: 'p', text: 'Just a short drive from The Florida Havens, the Brevard Zoo in Viera is one of the Space Coast’s most beloved family attractions. Known for its interactive exhibits and immersive animal encounters, it’s the perfect half-day or full-day adventure during your Melbourne Beach or Indialantic stay. The perfect local day trip for the whole family.' },
    { t: 'p', text: 'Whether you’re visiting for a tournament at the nearby USSSA Space Coast Complex, cruising from Port Canaveral, or simply enjoying a beach vacation, the zoo adds a fun and memorable experience for guests of all ages.' },
    { t: 'h2', text: '🐾 Why Visit Brevard Zoo?' },
    { t: 'p', text: 'Unlike large city zoos that can feel overwhelming, Brevard Zoo offers a more walkable, engaging experience — with opportunities to get closer to wildlife than you might expect.' },
    { t: 'h2', text: '📍 Convenient Location Near Our Properties' },
    { t: 'p', text: 'Approximate drive time from Melbourne Beach: 20–25 minutes' },
    { t: 'p', text: 'Approximate drive time from Indialantic: 20 minutes' },
    { t: 'p', text: 'Located in Viera, near the USSSA Space Coast Complex' },
    { t: 'p', text: 'Many guests visiting for baseball or softball tournaments choose to spend an off-day at the zoo. It’s also an excellent activity for cruise families arriving early or staying after disembarkation.' },
    { t: 'p', text: '📍 Planning Your Visit' },
    { t: 'p', text: 'Address: 8225 N Wickham Rd, Melbourne, FL 32940' },
    { t: 'p', text: 'Parking available on-site' },
    { t: 'p', text: 'Plan 3–4 hours for a comfortable visit' },
    { t: 'p', text: 'Morning visits are ideal during warmer months' },
    { t: 'p', text: '🦒 Giraffe Feedings' },
    { t: 'p', text: 'Get face-to-face with these gentle giants during scheduled feeding times — a guest favorite and great photo opportunity.' },
    { t: 'p', text: '🛶 Kayak Through Animal Habitats' },
    { t: 'p', text: 'One of the zoo’s most unique features is the chance to kayak through Expedition Africa, paddling past giraffes, rhinos, and lemurs in a lush, open environment.' },
    { t: 'p', text: '🌳 Treetop Trek Aerial Adventures' },
    { t: 'p', text: 'For families with older kids or adventurous adults, Brevard Zoo also offers zip lines and obstacle courses above the zoo grounds.' },
    { t: 'p', text: '🏡 Why Stay at The Florida Havens?' },
    { t: 'p', text: 'After a day exploring Brevard Zoo, return to the peace and comfort of your private beach retreat.' },
    { t: 'p', text: '✔️ Spacious homes ideal for families' },
    { t: 'p', text: '✔️ Full kitchens for easy meals' },
    { t: 'p', text: '✔️ Direct beach access' },
    { t: 'p', text: '✔️ Quiet coastal setting away from busy tourist corridors' },
    { t: 'p', text: '✔️ Central location near Viera, Port Canaveral & Orlando day trips' },
  ],
  'stay-near-space-coast-rocket-launches-kennedy-space-center-beach-house': [
    { t: 'h2', text: 'Rocket Launches, NASA & Why This Area Is Called “The Space Coast”' },
    { t: 'p', text: 'When you stay at The Florida Havens, you’re not just visiting the beach — you’re staying in one of the most historically significant space regions in the world.' },
    { t: 'p', text: 'Florida’s Space Coast earned its name because it is home to Kennedy Space Center, Cape Canaveral Space Force Station, and some of the most important rocket launches in American history.' },
    { t: 'p', text: 'From Apollo moon missions to today’s SpaceX Falcon 9 launches, this stretch of coastline continues to make history — and you can often watch it happen live during your stay.' },
    { t: 'p', text: '🛰️ Kennedy Space Center Visitor Complex' },
    { t: 'p', text: 'Located about 1 hour north of Melbourne Beach, the Kennedy Space Center Visitor Complex is one of Florida’s most inspiring attractions.' },
    { t: 'p', text: 'Here, you can:' },
    { t: 'p', text: 'Stand beneath the massive Saturn V rocket' },
    { t: 'p', text: 'Visit the Space Shuttle Atlantis exhibit' },
    { t: 'p', text: 'Meet veteran NASA astronauts' },
    { t: 'p', text: 'Experience immersive launch simulations' },
    { t: 'p', text: 'Learn about Artemis missions and future moon exploration' },
    { t: 'p', text: 'It’s an unforgettable experience for families, space enthusiasts, and anyone curious about America’s space legacy. 📍 Location: Merritt Island, FL' },
    { t: 'p', text: 'VISIT THE SPACE CENTER' },
    { t: 'p', text: 'NASA SCHEDULE' },
    { t: 'p', text: '🚀 Watch Real Rocket Launches During Your Stay' },
    { t: 'p', text: 'One of the most unique aspects of visiting the Space Coast is the opportunity to witness live rocket launches from:' },
    { t: 'p', text: 'NASA' },
    { t: 'p', text: 'SpaceX' },
    { t: 'p', text: 'United Launch Alliance (ULA)' },
    { t: 'p', text: 'Blue Origin' },
    { t: 'p', text: 'Depending on weather and schedule, launches can often be seen from beaches near our properties — sometimes even from your vacation rental.' },
    { t: 'p', text: 'There’s nothing quite like watching a rocket ascend into the sky over the Atlantic Ocean.' },
    { t: 'p', text: 'You can check the current launch schedule here:' },
    { t: 'p', text: 'SPACEX SCHEDULE' },
    { t: 'p', text: '🌊 Best Local Rocket Launch Viewing Spots' },
    { t: 'p', text: 'Guests often watch launches from:' },
    { t: 'p', text: 'Melbourne Beach shoreline' },
    { t: 'p', text: 'Indialantic Beach shoreline' },
    { t: 'p', text: 'Sebastian Inlet' },
    { t: 'p', text: 'Jetty Park (near Port Canaveral)' },
    { t: 'p', text: 'Cocoa Beach & Pier' },
    { t: 'p', text: 'Clear evenings and early mornings provide spectacular viewing conditions.' },
    { t: 'p', text: 'LIST OF BEST SPOTS' },
    { t: 'p', text: '🧑‍🚀 American Space Museum & Space Walk of Fame:' },
    { t: 'p', text: 'Located in nearby Titusville, the American Space Museum & Space Walk of Fame offers a more intimate, insider look at the people and technology behind America’s space program.' },
    { t: 'p', text: 'What You’ll Experience:' },
    { t: 'p', text: 'Authentic artifacts from the Mercury, Gemini, Apollo and Shuttle programs' },
    { t: 'p', text: 'Mission control equipment and launch hardware' },
    { t: 'p', text: 'Rare spaceflight memorabilia' },
    { t: 'p', text: 'Interactive exhibits and educational displays' },
    { t: 'p', text: 'Personal stories from NASA and aerospace professionals' },
    { t: 'p', text: 'Space Walk of Fame honoring the heroes of the space program' },
    { t: 'p', text: 'VISIT THE SPACE MUSEUM' },
    { t: 'p', text: '🏡 Why Stay at The Florida Havens for Your Space Coast Visit?' },
    { t: 'p', text: '✔️ Central location between Melbourne Beach and Cape Canaveral' },
    { t: 'p', text: '✔️ Peaceful oceanfront setting away from heavy tourism traffic' },
    { t: 'p', text: '✔️ Easy drive to Kennedy Space Center' },
    { t: 'p', text: '✔️ Front-row seats to rocket launch skies' },
    { t: 'p', text: '✔️ Spacious accommodations for families' },
    { t: 'p', text: 'Few places in the world allow you to relax on the beach in the morning and witness a live rocket launch by evening.' },
    { t: 'p', text: 'That’s what makes Florida’s Space Coast truly special.' },
  ],
  'terms-and-conditions': [
    { t: 'p', text: 'These Terms and Conditions constitute the Rental Agreement between you and The Florida Havens for your stay at any of our properties. By booking through our website or the Guesty booking platform, you acknowledge and agree to these Terms and Conditions, which govern your rental. You also agree to be bound by Guesty’s general platform Terms of Service where applicable. In the event of any conflict, these Rental Terms shall prevail with respect to your booking and stay.' },
    { t: 'p', text: '1. Booking, Payment, and Occupancy' },
    { t: 'p', text: 'A valid credit card is required to secure a reservation. Full payment is due at the time of booking unless otherwise arranged.' },
    { t: 'p', text: 'All rates displayed include applicable taxes and the final cleaning fee.' },
    { t: 'p', text: 'The primary booker must be at least 25 years of age and must occupy the property for the entire duration of the stay.' },
    { t: 'p', text: 'Maximum occupancy is strictly limited to the number of guests specified in your booking confirmation. Only registered guests are permitted. Unregistered visitors require prior written approval.' },
    { t: 'p', text: '2. Cancellation and Refund Policy' },
    { t: 'p', text: 'Cancellations made 60 days or more before check-in: Full refund minus a 5% processing fee.' },
    { t: 'p', text: 'Cancellations made fewer than 60 days before check-in: No refund. We may, at our sole discretion, offer a credit for a future stay (subject to availability and blackout dates).' },
    { t: 'p', text: 'No-shows: The entire stay will be charged with no refund.' },
    { t: 'p', text: 'Changes to booking dates are treated as a cancellation and new booking.' },
    { t: 'p', text: 'We strongly recommend purchasing travel insurance to protect against cancellations, illness, or other unforeseen events.' },
    { t: 'p', text: 'Force Majeure events are addressed in Section 8.' },
    { t: 'p', text: '3. Check-in / Check-out' },
    { t: 'p', text: 'Check-in: 3:00 PM' },
    { t: 'p', text: 'Check-out: 10:00 AM' },
    { t: 'p', text: 'Early check-in and late check-out requests are subject to availability and may incur additional fees. They are not guaranteed.' },
    { t: 'p', text: 'Access instructions and lock codes will be provided prior to arrival. You are responsible for securing the property.' },
    { t: 'p', text: '4. House Rules' },
    { t: 'p', text: 'No Smoking / Vaping: Strictly prohibited inside the home and on all outdoor areas.' },
    { t: 'p', text: 'No Pets / Animals / ESAs: Pets, animals, and emotional support animals are not permitted under any circumstances.' },
    { t: 'p', text: 'Reason: The property owner has severe, documented allergies. Short-term vacation rentals in Florida (Chapter 509) are not considered “dwellings” under the Fair Housing Act. Booking constitutes acceptance of this policy.' },
    { t: 'p', text: 'Any violation will result in immediate cancellation of the reservation without refund and possible forfeiture of the damage deposit.' },
    { t: 'p', text: 'No Parties or Events: Large gatherings, parties, or events are prohibited without prior written consent.' },
    { t: 'p', text: 'Quiet Hours: 10:00 PM to 8:00 AM. Excessive noise or disruptive behavior is not tolerated.' },
    { t: 'p', text: 'Security Cameras: Exterior security cameras are installed for the safety and security of our guests and the property. These cameras monitor only exterior areas (entrances, driveway, and grounds). There are no interior cameras or recordings of any kind inside the homes.' },
    { t: 'p', text: 'Sea Turtle Protection (May–October): Strict compliance with beach lighting, no fires, and nesting area rules is required.' },
    { t: 'p', text: 'Guests are fully responsible for the conduct of all members of their party. Please practice common decency and respect toward our properties, fellow guests, and neighbors.' },
    { t: 'p', text: '5.Property Care, Damages, and Cleaning' },
    { t: 'p', text: 'Guests must treat the property with care and leave it in good condition.' },
    { t: 'p', text: 'A security/damage deposit (amount specified at booking) is required. It will be refunded within 14 business days after departure, less any deductions for damages beyond normal wear and tear, excessive cleaning, missing items, or other violations.' },
    { t: 'p', text: 'You are financially responsible for any damage beyond normal wear and tear, including costs caused by your group.' },
    { t: 'p', text: 'Report any pre-existing damage or issues immediately upon arrival.' },
    { t: 'p', text: 'Additional cleaning or trash removal fees will apply if the property is not left reasonably clean.' },
    { t: 'p', text: '6. Property Condition and Amenities' },
    { t: 'p', text: 'The property, including appliances, furnishings, pool/spa, and beach access, is provided “AS IS”. We are not responsible for interruptions in utilities, internet, cable, or pool heating. Minor issues will not result in refunds.' },
    { t: 'p', text: '7. Liability and Insurance' },
    { t: 'p', text: 'The Florida Havens, its owners, managers, and affiliates are not liable for any personal injury, death, loss, or damage to personal property occurring during your stay.' },
    { t: 'p', text: 'Use of the pool, spa, beach, and all amenities is at your own risk. Children must be supervised by an adult at all times, especially near the pool and beach.' },
    { t: 'p', text: 'Guests assume all risk and agree to indemnify and hold harmless The Florida Havens from any claims, damages, or liabilities arising from their stay or actions of their party.' },
    { t: 'p', text: 'We strongly recommend comprehensive travel insurance that covers trip cancellation, interruption, medical emergencies, and personal property.' },
    { t: 'p', text: '8. Force Majeure' },
    { t: 'p', text: 'We are not responsible for events beyond our reasonable control (hurricanes, severe weather, pandemics, government orders, etc.). In such cases, we will work with you on rescheduling or a partial credit/refund at our sole discretion. No full refunds will be issued solely for weather-related concerns.' },
    { t: 'p', text: '9. Termination of Stay' },
    { t: 'p', text: 'We reserve the right to terminate your stay immediately and without refund if you violate these Terms, House Rules, or applicable laws. You must vacate the property promptly upon request.' },
    { t: 'p', text: '10. Governing Law and Dispute Resolution' },
    { t: 'p', text: 'These Terms are governed by the laws of the State of Florida. Any disputes shall be brought exclusively in the courts of Brevard County, Florida. The prevailing party in any legal action shall be entitled to recover its reasonable attorney’s fees and costs.' },
    { t: 'p', text: '11. Miscellaneous' },
    { t: 'p', text: 'These Terms, your booking confirmation, and the property-specific House Rules/Guidebook constitute the entire agreement between the parties.' },
    { t: 'p', text: 'If any provision is held invalid, the remainder of the Terms shall remain in effect.' },
    { t: 'p', text: 'We may update these Terms from time to time. Continued use after changes constitutes acceptance.' },
    { t: 'p', text: 'By completing your booking, you electronically consent to these Terms and Conditions.' },
    { t: 'p', text: 'We operate in full compliance with Florida DBPR licensing and tax collection requirements.' },
    { t: 'p', text: 'Contact Us' },
    { t: 'p', text: 'The Florida Havens Email: relax@thefloridahavens.com' },
    { t: 'p', text: 'Phone: (321) 209-0495' },
  ],
  'things-to-do-indialantic-melbourne-beach': [
    { t: 'p', text: 'When you stay at The Florida Havens, you’re not just near world-famous destinations — you’re surrounded by some of the Space Coast’s most charming local attractions.' },
    { t: 'p', text: 'From walkable beachside communities and scenic oceanfront parks to riverfront dining and historic downtown streets, Indialantic, Melbourne Beach, and Melbourne each offer their own unique personality.' },
    { t: 'p', text: 'Whether you’re looking for laid-back coastal vibes, outdoor adventure, or local dining favorites, you’ll find plenty to explore just minutes from your stay.' },
    { t: 'p', text: '🌆 Historic Downtown Melbourne (Approx. 10 Minutes)' },
    { t: 'p', text: 'Spend an evening exploring Historic Downtown Melbourne along New Haven Avenue, home to locally owned restaurants, boutiques, wine bars, breweries, and live music venues.' },
    { t: 'p', text: 'It’s the perfect place for dinner after the beach or a relaxed night out during your stay.' },
    { t: 'p', text: '👉 Discover Historic Downtown Melbourne:' },
    { t: 'p', text: 'EXPLORE HISTORIC MELBOURNE' },
    { t: 'p', text: '🎨 Eau Gallie Arts District (EGAD) (Approx. 10–15 Minutes)' },
    { t: 'p', text: 'Looking for local culture and creativity? The Eau Gallie Arts District (EGAD) is Melbourne’s vibrant arts hub, filled with galleries, murals, boutique shops, breweries, and live events.' },
    { t: 'p', text: 'Stroll colorful streets, browse local art studios, and enjoy monthly art walks and community festivals.' },
    { t: 'p', text: '👉 Explore the Eau Gallie Arts District:' },
    { t: 'p', text: 'VISIT EGAD' },
    { t: 'p', text: '🥕 Downtown Melbourne Farmers Market (Seasonal)' },
    { t: 'p', text: 'Visiting on a weekend? The Downtown Melbourne Farmers Market at Riverview Park features local produce, baked goods, food trucks, handmade items, and live music.' },
    { t: 'p', text: 'Overlooking the Indian River Lagoon, it’s a charming way to spend a Saturday morning.' },
    { t: 'p', text: '👉 Learn more about the Farmers Market:' },
    { t: 'p', text: 'VISIT FARMERS MARKET' },
    { t: 'p', text: '🎭 Henegar Center for the Arts (Downtown Melbourne)' },
    { t: 'p', text: 'Catch a live performance at the historic Henegar Center for the Arts, offering Broadway-style productions, concerts, youth theater, and community events throughout the year.' },
    { t: 'p', text: 'It’s a cultural gem just minutes from the beach.' },
    { t: 'p', text: '👉 View upcoming performances:' },
    { t: 'p', text: 'VISIT HENEGAR CENTER' },
    { t: 'p', text: '🐢 Archie Carr National Wildlife Refuge (Sea Turtle Nesting)' },
    { t: 'p', text: 'One of the most special features of staying in Melbourne Beach is proximity to the Archie Carr National Wildlife Refuge — one of the most important sea turtle nesting habitats in the Western Hemisphere.' },
    { t: 'p', text: 'From May through October, thousands of sea turtles come ashore to nest along these protected beaches. Guests staying at The Florida Havens often witness nesting activity or hatchlings making their way to the ocean (with proper guidelines and respect for wildlife).' },
    { t: 'p', text: 'It’s a rare and unforgettable natural experience that makes The Florida Havens truly unique.' },
    { t: 'p', text: '👉 Learn more about Archie Carr National Wildlife Refuge:' },
    { t: 'p', text: 'LEARN MORE' },
    { t: 'p', text: '⛳ Spessard Holland Golf Course (Melbourne Beach – Oceanfront)' },
    { t: 'p', text: 'Want to golf with ocean views? Spessard Holland Golf Course is a scenic 18-hole public course located directly along the Atlantic Ocean in Melbourne Beach.' },
    { t: 'p', text: 'Enjoy coastal breezes, challenging fairways, and one of the most picturesque golf settings on Florida’s Space Coast.' },
    { t: 'p', text: '👉 View Spessard Holland Golf Course:' },
    { t: 'p', text: 'BOOK TEE TIME' },
    { t: 'p', text: '🏡 Why Stay at The Florida Havens?' },
    { t: 'p', text: '✔️ Steps from uncrowded Melbourne Beach shoreline' },
    { t: 'p', text: '✔️ Minutes to Downtown Melbourne, EGAD & riverfront dining' },
    { t: 'p', text: '✔️ Close to golf, arts, farmers markets & live theater' },
    { t: 'p', text: '✔️ Peaceful coastal neighborhoods away from heavy tourism traffic' },
    { t: 'p', text: '✔️ Spacious homes perfect for families, couples & extended stays' },
    { t: 'p', text: 'Few places offer the ability to spend the morning watching sea turtles along a protected shoreline, the afternoon browsing art galleries or golfing by the ocean, and the evening enjoying live theater or dinner downtown.' },
    { t: 'p', text: 'That’s the beauty of staying on Florida’s Space Coast — relaxed beach living with culture, recreation, and charm just minutes away.' },
  ],
  'travel-with-your-pets': [
    { t: 'p', text: 'At The Florida Havens, we know that pets are cherished members of your family, and we truly appreciate how important it is to bring them with you on vacation. ❤️' },
    { t: 'p', text: 'To ensure the comfort, safety, and allergy-friendly experience of all our guests, we maintain a strict no-pets policy at our properties. That said, we’d love to help make your trip as seamless as possible — including finding a great place for your pet to stay nearby while you enjoy your beach getaway. Below are a few trusted local pet care and boarding options within roughly 15 minutes of both Indialantic and Melbourne Beach, FL.' },
    { t: 'p', text: 'We hope this helps you plan with peace of mind — and we’re always happy to assist with questions or recommendations!' },
    { t: 'h2', text: 'LOCAL PET BOARDING OPTIONS' },
    { t: 'p', text: '1. K9 KAMPUS - Popular dog care and boarding center in nearby Melbourne with excellent reviews and lots of activity options. (Great for dogs needing exercise or playtime.)' },
    { t: 'p', text: '2. PREPPY PET MELBOURNE - Trusted boarding and dog daycare facility in Melbourne with spacious play areas and overnight care.' },
    { t: 'p', text: '3. DOGVACAY.COM - If your pet does better in a home setting, you can book a local, background-checked sitter to host your pet in their home nearby. https://www.rover.com/indialantic--fl--pet-boarding/?utm_source=chatgpt.com' },
    { t: 'p', text: '4. ROVER/WAG - You can also find trusted sitters through apps like Rover or Wag! that connect you with vetted caregivers who can provide pet boarding, drop-in care, or overnight stays in their home.' },
  ],
  'usssa-space-coast-complex-vacation-rental': [
    { t: 'h2', text: 'A Home Base for Tournament Travel & Family Fun' },
    { t: 'p', text: 'Every year thousands of athletes, families, and teams travel to the USSSA Space Coast Complex — a premier destination sports facility right here in Brevard County — for baseball and softball tournaments, showcases, and games.' },
    { t: 'p', text: 'Whether you’re in town for competition, cheering from the stands, or planning a multi-day tournament getaway, The Florida Havens make the perfect home base:' },
    { t: 'p', text: '🏖️ Relaxing beach retreat after long days of games' },
    { t: 'p', text: '🚗 Easy, stress-free drive to and from the fields' },
    { t: 'p', text: '🍔 Close to local restaurants, shops, and family attractions' },
    { t: 'p', text: 'From youth baseball championships to fastpitch tournaments and World Series-level events, our properties offer comfort, convenience, and the space your team deserves.' },
    { t: 'p', text: '📌 Travel & Planning Tips' },
    { t: 'p', text: 'Distance to USSSA Space Coast Complex:' },
    { t: 'p', text: 'Our properties are a short ~30 minute drive to Viera — easy for early game times and quick returns.' },
    { t: 'p', text: 'Book early: Tournaments often sell out accommodation fast.' },
    { t: 'p', text: 'Local attractions: Extend your trip with beaches, parks, and Space Coast sights.' },
    { t: 'p', text: '🏟️ About The USSSA Space Coast Complex' },
    { t: 'p', text: 'The USSSA Space Coast Complex in Viera, FL is recognized as one of the nation’s top youth sports facilities — hosting major baseball and softball tournaments throughout the year. With 15 all-turf fields, multi-purpose stadiums, and a variety of events for athletes of all ages, it’s a hub for competitive play and family gatherings alike.' },
    { t: 'p', text: '📍 Address: USSSA Space Coast Complex' },
    { t: 'p', text: '5800 Stadium Parkway, Viera, FL 32940' },
    { t: 'p', text: 'VISIT WEBSITE' },
    { t: 'p', text: '🎉 Upcoming Tournament Highlights' },
    { t: 'p', text: 'Families travel from across the U.S. to witness and participate in marquee USSSA events like:' },
    { t: 'p', text: 'Space Coast World Series – National championships for ages 8U–18U (June each year)' },
    { t: 'p', text: 'Space Coast Spring Games – Multi-week youth tournament festival' },
    { t: 'p', text: 'Florida Slowpitch & Challenge Cups – Competitive youth and adult events' },
    { t: 'p', text: 'Fastpitch All American Games – Showcase opportunities for elite players (summer)' },
    { t: 'p', text: 'Space Coast Invitational tournaments and other regional competitions' },
    { t: 'p', text: '👉 These tournaments often draw hundreds of teams, coaches, and fans — making the Space Coast one of the most dynamic sports travel destinations in Florida.' },
    { t: 'p', text: 'SEE UPCOMING EVENTS' },
    { t: 'p', text: '🏡 Why Book The Florida Havens for Your USSSA Visit?' },
    { t: 'p', text: 'Staying with us brings advantages that hotel rooms simply don’t:' },
    { t: 'p', text: 'Spacious living areas and full kitchens — perfect for teams, families, and groups' },
    { t: 'p', text: 'Beach access and relaxation after games' },
    { t: 'p', text: 'Ample parking for multiple vehicles' },
    { t: 'p', text: 'Ideal position between Melbourne Beach, Indialantic, and Viera' },
    { t: 'p', text: 'Local spots for team dinners and celebratory meals' },
    { t: 'p', text: 'Whether you’re visiting for a weekend tournament or a week of competition, our homes provide a comfortable, convenient base for your stay.' },
  ],
}
