#!/usr/bin/env python3
"""Migrate body copy from the live Wix pages into content/page-body.ts.

Fetches each page, strips Wix chrome, and emits typed blocks. Section headings
are normalised to level 2/3 because the live pages jump from <h1> to <h5>.

Boilerplate detection is frequency-based rather than hardcoded: any text block
appearing on >=5 of the fetched pages is treated as site chrome (footer,
address strip, nav) and dropped.

Usage:  python3 tools/extract-copy.py           # fetch + regenerate
        python3 tools/extract-copy.py --local   # reuse ./live/*.html
"""
import html, json, os, re, sys, time, urllib.request
from collections import Counter

UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")
BASE = "https://www.thefloridahavens.com"

# Live Wix slugs whose copy we keep. Guides map to /guides/* via
# content/guides.ts (legacySlug); legal pages and /about are 1:1.
SLUGS = [
    "beach-house-near-orlando-theme-parks",
    "stay-near-space-coast-rocket-launches-kennedy-space-center-beach-house",
    "stay-near-brevard-zoo-melbourne-beach-house",
    "cape-canaveral-cruise-port-beach-stay",
    "beach-house-near-sebastian-inlet",
    "usssa-space-coast-complex-vacation-rental",
    "local-attractions-melbourne-beach",
    "things-to-do-indialantic-melbourne-beach",
    "best-restaurants-near-melbourne-beach-indialantic",
    "travel-with-your-pets",
    "privacy-policy", "terms-and-conditions", "refund-policy",
    "accessibility-statement", "about",
]

NAV = {"top of page", "Menu", "Close", "HOME", "ABOUT", "PROPERTIES",
       "BOOK YOUR STAY", "LOCAL ATTRACTIONS", "GUEST RESOURCES", "CONTACT",
       "bottom of page", "BOOK NOW", "Book Now", "THE FLORIDA HAVENS"}


def fetch(slug, outdir="live"):
    os.makedirs(outdir, exist_ok=True)
    path = os.path.join(outdir, slug + ".html")
    if os.path.exists(path):
        return path
    req = urllib.request.Request(f"{BASE}/{slug}", headers={"User-Agent": UA})
    for i in range(4):
        try:
            with urllib.request.urlopen(req, timeout=60) as r:
                open(path, "wb").write(r.read())
            time.sleep(1.3)          # Wix throttles hard; stay polite
            return path
        except Exception as e:
            if "429" in str(e) or "503" in str(e):
                time.sleep(4 * (i + 1))
            else:
                raise
    raise SystemExit(f"could not fetch {slug}")


def blocks(path):
    h = open(path, encoding="utf-8", errors="replace").read()
    h = re.sub(r"<(script|style|noscript)\b.*?</\1>", " ", h, flags=re.S | re.I)
    h = re.sub(r"<h([1-6])\b[^>]*>(.*?)</h\1>",
               lambda m: f"\n@@H{m.group(1)}@@{m.group(2)}\n", h, flags=re.S | re.I)
    h = re.sub(r"</(p|div|li|br)>", "\n", h, flags=re.I)
    h = re.sub(r"<li\b[^>]*>", "\n@@LI@@", h, flags=re.I)
    h = re.sub(r"<[^>]+>", "", h)
    h = html.unescape(h).replace("​", "")

    out = []
    for raw in h.split("\n"):
        t = re.sub(r"[ \t]+", " ", raw).strip()
        if not t or t in NAV or len(t) < 3:
            continue
        if t.startswith("@@H"):
            lvl, txt = int(t[3]), t[6:].strip()
            if txt and txt not in NAV:
                out.append(("h", lvl, txt))
        elif t.startswith("@@LI@@"):
            if t[6:].strip():
                out.append(("li", 0, t[6:].strip()))
        else:
            out.append(("p", 0, t))

    ded = []
    for b in out:
        if ded and ded[-1] == b:
            continue
        ded.append(b)
    c = Counter(b[2] for b in ded)
    return [b for b in ded if c[b[2]] <= 2]


def main():
    raw = {s: blocks(fetch(s)) for s in SLUGS}

    seen = Counter()
    for bs in raw.values():
        for t in {b[2] for b in bs}:
            seen[t] += 1
    chrome = {t for t, n in seen.items() if n >= 5}

    clean = {}
    for slug, bs in raw.items():
        out = [list(b) for b in bs
               if b[2] not in chrome
               and b[2].strip() not in ("-->", "<!--")
               and not re.match(r"^[A-Z].*\|\s*The Florida Havens$", b[2])]
        while out and re.match(
            r"^([A-Z][a-z]+,?\s*(FL|Florida)\s*\d{5}|\d{3}[-.]\d{3}[-.]\d{4}|.{0,3})$",
            out[-1][2],
        ):
            out.pop()
        clean[slug] = out

    def esc(s):
        return s.replace("\\", "\\\\").replace("'", "\\'")

    L = ['/**', ' * Body copy migrated verbatim from the live Wix pages.', ' *',
         ' * GENERATED by tools/extract-copy.py — do not hand-edit.', ' */',
         "export type Block =", "  | { t: 'h2'; text: string }",
         "  | { t: 'h3'; text: string }", "  | { t: 'p'; text: string }",
         "  | { t: 'li'; text: string }", "",
         "export const PAGE_BODY: Record<string, Block[]> = {"]
    for slug in sorted(clean):
        L.append(f"  '{slug}': [")
        seen_h1 = False
        for kind, lvl, txt in clean[slug]:
            if kind == "h":
                if lvl == 1 and not seen_h1:
                    seen_h1 = True
                    continue
                t = "h2" if lvl <= 5 else "h3"
            else:
                t = "li" if kind == "li" else "p"
            L.append(f"    {{ t: '{t}', text: '{esc(txt)}' }},")
        L.append("  ],")
    L.append("}")

    open("content/page-body.ts", "w").write("\n".join(L) + "\n")
    json.dump(clean, open("data/page-copy.json", "w"), indent=1)
    words = sum(len(b[2].split()) for v in clean.values() for b in v if b[0] in ("p", "li"))
    print(f"wrote content/page-body.ts — {len(clean)} pages, ~{words} words")


if __name__ == "__main__":
    main()
